            Node a = new Node();
            a.Colors.Add(Colors.Blue);
            a.Colors.Add(Colors.Green);
            a.Text = "A";
            test.Nodes.Add(a);
            Node b = new Node();
            b.Colors.Add(Colors.Red);
            b.Colors.Add(Colors.Green);
            b.Colors.Add(Colors.Yellow);
            b.Colors.Add(Colors.Gainsboro);
            b.Text = "123.111.123.111";
            test.Nodes.Add(b);
            Node c = new Node();
            c.Colors.Add(Colors.Blue);
            test.Nodes.Add(c);
            c.Text = "C";
            Node d = new Node();
            test.Nodes.Add(d);
            Node e = new Node();
            e.Colors.Add(Colors.Blue);
            e.Colors.Add(Colors.Green);
            test.Nodes.Add(e);
            Edge e1 = new Edge();
            e1.First = a;
            e1.Second = b;
            e1.Text = "ABC";
            test.Edges.Add(e1);
            Edge e2 = new Edge();
            e2.First = a;
            e2.Second = e;
            e2.Text = "123";
            test.Edges.Add(e2);
            Edge e3 = new Edge();
            e3.First = c;
            e3.Second = e;
            e3.Text = "111";
            test.Edges.Add(e3);

